spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: contract-service-error.dlq
              dlqPartitions: 2
              dlqProducerProperties:
                topic:
                  properties:
                    retention.ms: 86400000
      bindings:
        output:
          destination: output-topic
          producer:
            partitionCount: 4
        input:
          destination: input-topic
          producer:
            partitionCount: 4
          group: contract-service
  application:
    name: creams-contract-service
server:
  port: 8082
